Try using older version of sonar-maven-plugin,
https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/issues/167

WARNING: Error injecting: org.sonarsource.scanner.maven.SonarQubeMojo
java.lang.TypeNotPresentException: Type org.sonarsource.scanner.maven.SonarQubeMojo not present
[..]
Caused by: java.lang.UnsupportedClassVersionError: org/sonarsource/scanner/maven/SonarQubeMojo : Unsupported major.minor version 52.0